### ISSUE TITLE
Gracefully handle when ATOMIST_TEAM environment variable is not set

### ISSUE THREAD

**Issue by ddgenome** [atomist/spring-boot-agent#2]
With this application.yml

```yaml
logging:
   level:
     com.atomist.spring.agent: DEBUG

atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/${ATOMIST_TEAM}'
  environment:
      domain: '${vcap.application.space_name:development}'
      pod: '${HOSTNAME:${random.value}}'
```

if the `ATOMIST_TEAM` environment variable is not set, tests fail and the application will not start:

```
Binding to target com.atomist.spring.agent.AgentConfigurationProperties@3cae7b8b failed:

    Property: atomist.url
    Value: https://webhook.atomist.com/atomist/application/teams/${ATOMIST_TEAM}
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.net.URI' for property 'url'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.net.URI]
```

Is there a way to just leave `atomist.url` unset if `ATOMIST_TEAM` is not set?
